<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Member;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            [
                'name' => 'Pastor John Santos',
                'email' => 'pastor.john@church.com',
                'phone' => '+63 912 345 6789',
                'address' => '123 Main Street, Sorsogon City, Sorsogon',
                'join_date' => '2020-01-15',
                'status' => 'active',
                'role' => 'Pastor',
                'gender' => 'Male',
                'birthday' => '1980-05-20',
            ],
            [
                'name' => 'Sister Maria Garcia',
                'email' => 'maria.garcia@church.com',
                'phone' => '+63 923 456 7890',
                'address' => '456 Coastal Road, Bulan, Sorsogon',
                'join_date' => '2019-03-10',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Female',
                'birthday' => '1985-08-15',
            ],
            [
                'name' => 'Brother Carlos Rodriguez',
                'email' => 'carlos.rodriguez@church.com',
                'phone' => '+63 934 567 8901',
                'address' => '789 Beach Street, Gubat, Sorsogon',
                'join_date' => '2018-07-22',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Male',
                'birthday' => '1978-12-03',
            ],
            [
                'name' => 'Sister Ana Martinez',
                'email' => 'ana.martinez@church.com',
                'phone' => '+63 945 678 9012',
                'address' => '321 Mountain View, Bulusan, Sorsogon',
                'join_date' => '2021-02-14',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Female',
                'birthday' => '1990-04-25',
            ],
            [
                'name' => 'Brother Luis Fernandez',
                'email' => 'luis.fernandez@church.com',
                'phone' => '+63 956 789 0123',
                'address' => '654 Rural Road, Casiguran, Sorsogon',
                'join_date' => '2017-11-08',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Male',
                'birthday' => '1982-09-12',
            ],
            [
                'name' => 'Sister Elena Cruz',
                'email' => 'elena.cruz@church.com',
                'phone' => '+63 967 890 1234',
                'address' => '987 Whale Street, Pilar, Sorsogon',
                'join_date' => '2020-06-30',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Female',
                'birthday' => '1987-01-18',
            ],
            [
                'name' => 'Pastor David Reyes',
                'email' => 'pastor.david@church.com',
                'phone' => '+63 978 901 2345',
                'address' => '147 Church Street, Sorsogon City, Sorsogon',
                'join_date' => '2016-04-05',
                'status' => 'active',
                'role' => 'Pastor',
                'gender' => 'Male',
                'birthday' => '1975-11-30',
            ],
            [
                'name' => 'Sister Rosa Lopez',
                'email' => 'rosa.lopez@church.com',
                'phone' => '+63 989 012 3456',
                'address' => '258 Faith Avenue, Bulan, Sorsogon',
                'join_date' => '2019-09-12',
                'status' => 'active',
                'role' => 'Leader',
                'gender' => 'Female',
                'birthday' => '1983-07-08',
            ],
            [
                'name' => 'Brother Mark Dela Cruz',
                'email' => 'mark.delacruz@church.com',
                'phone' => '+63 900 111 2222',
                'address' => '100 Sunrise Blvd, Sorsogon City',
                'join_date' => '2022-03-10',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Male',
                'birthday' => '1995-03-15',
            ],
            [
                'name' => 'Sister Grace Lim',
                'email' => 'grace.lim@church.com',
                'phone' => '+63 900 222 3333',
                'address' => '200 Sunset Ave, Gubat, Sorsogon',
                'join_date' => '2023-01-20',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Female',
                'birthday' => '1998-07-22',
            ],
            [
                'name' => 'Brother Joseph Tan',
                'email' => 'joseph.tan@church.com',
                'phone' => '+63 900 333 4444',
                'address' => '300 River Road, Bulusan, Sorsogon',
                'join_date' => '2021-11-05',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Male',
                'birthday' => '1992-12-10',
            ],
            [
                'name' => 'Sister Liza Ramos',
                'email' => 'liza.ramos@church.com',
                'phone' => '+63 900 444 5555',
                'address' => '400 Lakeview St, Pilar, Sorsogon',
                'join_date' => '2022-07-18',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Female',
                'birthday' => '1997-05-30',
            ],
            [
                'name' => 'Brother Peter Cruz',
                'email' => 'peter.cruz@church.com',
                'phone' => '+63 900 555 6666',
                'address' => '500 Hilltop Dr, Casiguran, Sorsogon',
                'join_date' => '2023-04-12',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Male',
                'birthday' => '1994-09-18',
            ],
            [
                'name' => 'Sister Joy Bautista',
                'email' => 'joy.bautista@church.com',
                'phone' => '+63 900 666 7777',
                'address' => '600 Ocean Dr, Sorsogon City',
                'join_date' => '2021-09-25',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Female',
                'birthday' => '1996-11-02',
            ],
            [
                'name' => 'Brother Samuel Uy',
                'email' => 'samuel.uy@church.com',
                'phone' => '+63 900 777 8888',
                'address' => '700 Palm St, Bulan, Sorsogon',
                'join_date' => '2022-12-01',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Male',
                'birthday' => '1993-08-25',
            ],
            [
                'name' => 'Sister Carla Mendoza',
                'email' => 'carla.mendoza@church.com',
                'phone' => '+63 900 888 9999',
                'address' => '800 Forest Lane, Gubat, Sorsogon',
                'join_date' => '2023-02-14',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Female',
                'birthday' => '1999-04-12',
            ],
            [
                'name' => 'Brother Alex Gomez',
                'email' => 'alex.gomez@church.com',
                'phone' => '+63 900 999 0000',
                'address' => '900 Baywalk, Sorsogon City',
                'join_date' => '2022-10-10',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Male',
                'birthday' => '1991-06-17',
            ],
            [
                'name' => 'Sister Nina Santos',
                'email' => 'nina.santos@church.com',
                'phone' => '+63 900 000 1111',
                'address' => '1000 Garden St, Bulusan, Sorsogon',
                'join_date' => '2023-03-22',
                'status' => 'active',
                'role' => 'Member',
                'gender' => 'Female',
                'birthday' => '1998-10-05',
            ],
        ];

        foreach ($members as $member) {
            Member::create($member);
        }
    }
} 