<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('QR Code Management') }}
            </h2>
            <a href="{{ route('attendance.qr-management', $qrCode->event) }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                <i class="fas fa-arrow-left mr-2"></i>Back to Event
            </a>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <!-- Event Information -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg mb-6">
                <div class="p-6 text-gray-900">
                    <div class="flex items-center justify-between">
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900">{{ $qrCode->event->title }}</h3>
                            <div class="text-gray-600 mt-1">
                                <span class="mr-4"><i class="fas fa-calendar-alt mr-1"></i>{{ $qrCode->event->date->format('l, F j, Y') }}</span>
                                @if($qrCode->event->time)
                                    <span class="mr-4"><i class="fas fa-clock mr-1"></i>{{ $qrCode->event->time }}</span>
                                @endif
                                @if($qrCode->event->location)
                                    <span><i class="fas fa-map-marker-alt mr-1"></i>{{ $qrCode->event->location }}</span>
                                @endif
                            </div>
                        </div>
                        <div class="text-right">
                            <div class="text-sm text-gray-500">Generated by</div>
                            <div class="font-medium">{{ $qrCode->creator->name }}</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <!-- QR Code Display -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        <h3 class="text-lg font-semibold text-gray-900 mb-4">QR Code</h3>
                        
                        <div class="text-center">
                            <div class="bg-white p-4 rounded-lg shadow-lg inline-block mb-4">
                                <img src="{{ route('qr.image', $qrCode) }}" 
                                     alt="Attendance QR Code" 
                                     class="w-64 h-64 mx-auto">
                            </div>
                            
                            <div class="space-y-2 text-sm text-gray-600">
                                <p><strong>Code:</strong> {{ $qrCode->code }}</p>
                                <p><strong>Status:</strong> 
                                    @if($qrCode->isValid())
                                        <span class="text-green-600 font-medium">Active</span>
                                    @else
                                        <span class="text-red-600 font-medium">Inactive/Expired</span>
                                    @endif
                                </p>
                                <p><strong>Expires:</strong> {{ $qrCode->expires_at->format('M j, Y g:i A') }}</p>
                                <p><strong>Created:</strong> {{ $qrCode->created_at->format('M j, Y g:i A') }}</p>
                            </div>
                        </div>

                        <!-- Action Buttons -->
                        <div class="mt-6 space-y-3">
                            <a href="{{ route('qr.display', $qrCode) }}" 
                               target="_blank"
                               class="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-md transition-colors flex items-center justify-center">
                                <i class="fas fa-external-link-alt mr-2"></i>
                                Open Display Page
                            </a>
                            
                            @if($qrCode->isValid())
                                <form action="{{ route('qr.deactivate', $qrCode) }}" method="POST" class="w-full">
                                    @csrf
                                    <button type="submit" 
                                            class="w-full bg-red-600 hover:bg-red-700 text-white font-medium py-2 px-4 rounded-md transition-colors"
                                            onclick="return confirm('Are you sure you want to deactivate this QR code?')">
                                        <i class="fas fa-stop-circle mr-2"></i>
                                        Deactivate QR Code
                                    </button>
                                </form>
                            @endif
                        </div>
                    </div>
                </div>

                <!-- Real-time Attendance -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        <div class="flex items-center justify-between mb-4">
                            <h3 class="text-lg font-semibold text-gray-900">Real-time Attendance</h3>
                            <button onclick="refreshAttendance()" class="text-blue-600 hover:text-blue-800">
                                <i class="fas fa-sync-alt"></i>
                            </button>
                        </div>

                        <!-- Attendance Stats -->
                        <div class="grid grid-cols-2 gap-4 mb-6">
                            <div class="bg-green-50 p-4 rounded-lg text-center">
                                <div class="text-2xl font-bold text-green-600" id="totalPresent">0</div>
                                <div class="text-sm text-green-700">Present</div>
                            </div>
                            <div class="bg-blue-50 p-4 rounded-lg text-center">
                                <div class="text-2xl font-bold text-blue-600" id="totalScanned">0</div>
                                <div class="text-sm text-blue-700">Total Scanned</div>
                            </div>
                        </div>

                        <!-- Recent Scans -->
                        <div>
                            <h4 class="font-medium text-gray-900 mb-3">Recent Scans</h4>
                            <div id="recentAttendance" class="space-y-2 max-h-64 overflow-y-auto">
                                <!-- Recent attendance will be populated here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Instructions for Display -->
            <div class="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-6">
                <h3 class="text-lg font-semibold text-blue-900 mb-3">
                    <i class="fas fa-info-circle mr-2"></i>
                    How to Use This QR Code
                </h3>
                <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-blue-800">
                    <div>
                        <h4 class="font-medium mb-2">1. Display QR Code</h4>
                        <p>Click "Open Display Page" to show the QR code on a screen or projector for members to scan.</p>
                    </div>
                    <div>
                        <h4 class="font-medium mb-2">2. Members Scan</h4>
                        <p>Members can scan the QR code using their phone's camera or the scanner app.</p>
                    </div>
                    <div>
                        <h4 class="font-medium mb-2">3. Monitor Attendance</h4>
                        <p>Watch the real-time attendance updates in the right panel as members scan.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Auto-refresh attendance data every 10 seconds
        setInterval(refreshAttendance, 10000);
        
        // Initial load
        document.addEventListener('DOMContentLoaded', function() {
            refreshAttendance();
        });

        function refreshAttendance() {
            fetch(`{{ route('attendance.real-time') }}?event_id={{ $qrCode->event_id }}&date={{ today()->format('Y-m-d') }}`)
                .then(response => response.json())
                .then(data => {
                    document.getElementById('totalPresent').textContent = data.total_present;
                    document.getElementById('totalScanned').textContent = data.attendances.length;
                    
                    const recentContainer = document.getElementById('recentAttendance');
                    recentContainer.innerHTML = '';
                    
                    data.attendances.slice(0, 10).forEach(attendance => {
                        const time = new Date(attendance.scanned_at).toLocaleTimeString();
                        const item = document.createElement('div');
                        item.className = 'flex items-center justify-between p-3 bg-gray-50 rounded-lg';
                        item.innerHTML = `
                            <div>
                                <div class="font-medium text-gray-900">${attendance.member.name}</div>
                                <div class="text-sm text-gray-600">${time}</div>
                            </div>
                            <div class="text-green-600">
                                <i class="fas fa-check-circle"></i>
                            </div>
                        `;
                        recentContainer.appendChild(item);
                    });
                    
                    if (data.attendances.length === 0) {
                        recentContainer.innerHTML = '<p class="text-gray-500 text-center py-4">No attendance recorded yet</p>';
                    }
                })
                .catch(error => {
                    console.error('Error fetching attendance:', error);
                });
        }
    </script>
</x-app-layout> 